image: python:3.7

before_script:
  - echo "Before script!"

stages:
  - create-binary


dockerize:
  variables:
    CI_DEBUG_TRACE: "true"
    # enable verbose git output
    GIT_PUSH_FLAGS: "-vvv"
    # enable verbose ssh output
    GIT_SSH_COMMAND: "ssh -vvv"
  tags:
    - fw01
  stage: create-binary
  only:
    - main
  script:
    - echo "Performing direct binary execution"