image: python:3.7

before_script:
  - echo "Before script!"

stages:
  - create-binary

variables:
  REPO_NAME: https://git.apps.hexmos.com/hexmos/common/one-installer
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA

create-binary:
  # variables:
  #   CI_DEBUG_TRACE: "true"
  #   # enable verbose git output
  #   GIT_PUSH_FLAGS: "-vvv"
  #   # enable verbose ssh output
  #   GIT_SSH_COMMAND: "ssh -vvv"
  tags:
    - fw02
  stage: create-binary
  only:
    - main
  script:
    - echo "Performing direct binary execution"
    - time docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    # Run the Docker container to extract executor.bin and save it as an artifact
    - time docker build -t $TAG_COMMIT -t $TAG_LATEST .
    - time docker run --name one-installer -t $TAG_COMMIT /bin/true
    - time docker cp one-installer:/executor.bin executor.bin
  artifacts:
    paths:
      - executor.bin