image: python:3.7

before_script:
  - echo "Before script!"

stages:
  - create-binary

variables:
  IMAGE_NAME: one-installer

create-binary:
  # variables:
  #   CI_DEBUG_TRACE: "true"
  #   # enable verbose git output
  #   GIT_PUSH_FLAGS: "-vvv"
  #   # enable verbose ssh output
  #   GIT_SSH_COMMAND: "ssh -vvv"
  tags:
    - fw01
  stage: create-binary
  only:
    - main
  script:
    - echo "Performing direct binary execution"
    - docker build -t $IMAGE_NAME .
    # Run the Docker container to extract executor.bin and save it as an artifact
    - docker run --name one-installer $IMAGE_NAME /bin/true
    - docker cp one-installer:/executor.bin executor.bin
  artifacts:
    paths:
      - executor.bin